/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

#include "Utils/Logger.h"

#include "Params.h"

using namespace juce;

//==============================================================================
MonosynthAudioProcessor::MonosynthAudioProcessor()
{
	Utils::SetupLogger("monosynth.log");
	SETUP_PARAMS();
}

MonosynthAudioProcessor::~MonosynthAudioProcessor()
{
}

//==============================================================================
const String MonosynthAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

int MonosynthAudioProcessor::getNumParameters()
{
    return 0;
}

float MonosynthAudioProcessor::getParameter (int /*index*/)
{
    return 0.0f;
}

void MonosynthAudioProcessor::setParameter (int /*index*/, float /*newValue*/)
{
}

const String MonosynthAudioProcessor::getParameterName (int /*index*/)
{
    return String();
}

const String MonosynthAudioProcessor::getParameterText (int /*index*/)
{
    return String();
}

const String MonosynthAudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String MonosynthAudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool MonosynthAudioProcessor::isInputChannelStereoPair (int /*index*/) const
{
    return true;
}

bool MonosynthAudioProcessor::isOutputChannelStereoPair (int /*index*/) const
{
    return true;
}

bool MonosynthAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool MonosynthAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool MonosynthAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double MonosynthAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int MonosynthAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int MonosynthAudioProcessor::getCurrentProgram()
{
    return 0;
}

void MonosynthAudioProcessor::setCurrentProgram (int /*index*/)
{
}

const String MonosynthAudioProcessor::getProgramName (int /*index*/)
{
    return String();
}

void MonosynthAudioProcessor::changeProgramName (int /*index*/, const String& /*newName*/)
{
}

//==============================================================================
void MonosynthAudioProcessor::prepareToPlay (double sampleRate_, int samplesPerBlock)
{
    engine.PrepareToPlay(sampleRate_, samplesPerBlock);
}

void MonosynthAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void MonosynthAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
#if 0
    // In case we have more outputs than inputs, this code clears any output
    // channels that didn't contain input data, (because these aren't
    // guaranteed to be empty - they may contain garbage).
    // I've added this to avoid people getting screaming feedback
    // when they first compile the plugin, but obviously you don't need to
    // this code if your algorithm already fills all the output channels.
    for (int i = getNumInputChannels(); i < getNumOutputChannels(); ++i)
        buffer.clear (i, 0, buffer.getNumSamples());

    // This is the place where you'd normally do the guts of your plugin's
    // audio processing...
    for (int channel = 0; channel < getNumInputChannels(); ++channel)
    {
        float* channelData = buffer.getWritePointer (channel);

        // ..do something to the data...
    }
#endif

	engine.Process(buffer, midiMessages);
}

//==============================================================================
bool MonosynthAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* MonosynthAudioProcessor::createEditor()
{
    return new MonosynthAudioProcessorEditor (*this);
}

//==============================================================================
void MonosynthAudioProcessor::getStateInformation (MemoryBlock& /*destData*/)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void MonosynthAudioProcessor::setStateInformation (const void* /*data*/, int /*sizeInBytes*/)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new MonosynthAudioProcessor();
}
