/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "../Gui/MainGui.h"

//==============================================================================
/**
*/
class MonosynthAudioProcessorEditor  : public juce::AudioProcessorEditor
{
public:
    MonosynthAudioProcessorEditor (MonosynthAudioProcessor&);
    ~MonosynthAudioProcessorEditor();

    //==============================================================================
    void paint (juce::Graphics&) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    MonosynthAudioProcessor& processor;

	Gui::MainGui mainGui;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MonosynthAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
