/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "Utils/Logger.h"

//==============================================================================
MonosynthAudioProcessorEditor::MonosynthAudioProcessorEditor (MonosynthAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p), mainGui (p)
{
	LOG("Constructing AudioProcessorEditor");
	
	// Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    //setSize (400, 300);
	setSize(mainGui.getWidth(), mainGui.getHeight());

	LOG("Adding MainGui");

	addAndMakeVisible(&mainGui);

	LOG("Constructing AudioProcessorEditor complete");
}

MonosynthAudioProcessorEditor::~MonosynthAudioProcessorEditor()
{
}

//==============================================================================
void MonosynthAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);

    g.setColour (Colours::black);
    g.setFont (15.0f);
    g.drawFittedText ("Hello World!", getLocalBounds(), Justification::centred, 1);
}

void MonosynthAudioProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..
}
