/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "../Gui/MainGui.h"

//==============================================================================
/**
*/
class MonosynthAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    MonosynthAudioProcessorEditor (MonosynthAudioProcessor&);
    ~MonosynthAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    MonosynthAudioProcessor& processor;

	Gui::MainGui mainGui;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MonosynthAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
